repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    files: "PyExpLabSys"
    hooks:
    -   id: check-yaml
        files: PyExpLabSys
    -   id: end-of-file-fixer
        files: PyExpLabSys
    -   id: trailing-whitespace
        files: PyExpLabSys
